# Command file generated by Gnu17 Plug-in for Eclipse

#drill down into the debug directory
cd @project@/build/gdb

# flash program load
file @bin@/fls/@machine@.elf

# connect to the debugger with specified mode and port
target icd usb

# load flash program
load @bin@/fls/@machine@.elf

# flash set
c17 fls 0x8000 0x87fff FLASH_ERASE FLASH_LOAD

# flash sector erase
c17 fle 0x8000 0 0


# load debugging information in program
file @project@/build/gdb/@buildfile@.elf

# set the memory configuration map file to the debugger
c17 rpf @bin@/par/@machine@.par

# connect to the debugger with specified mode and port
# target [icd usb | sim]
target icd usb

# load program to memory
load @project@/build/gdb/@buildfile@.psa

# reset
c17 rst
